"""catalog schema

Revision ID: 299947282066
Revises: 
Create Date: 2026-09-16 18:09:57.216818

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '299947282066'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Required by ix_movies_title_trgm (gin_trgm_ops) for fuzzy title search.
    # Must run before that index is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('backdrop_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_keywords_name', 'keywords', ['name'], unique=False)
    op.create_table('movie_links',
    sa.Column('tmdb_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('movielens_id', sa.Integer(), nullable=False),
    sa.Column('imdb_numeric_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('tmdb_id')
    )
    op.create_index('ix_movie_links_movielens_id', 'movie_links', ['movielens_id'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('profile_path', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_people_name', 'people', ['name'], unique=False)
    op.create_table('movie_credits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('credit_type', sa.String(length=10), nullable=False),
    sa.Column('role', sa.String(length=500), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('billing_order', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movie_credits_person_id', 'movie_credits', ['person_id'], unique=False)
    op.create_index('ix_movie_credits_role', 'movie_credits', ['credit_type', 'role'], unique=False)
    op.create_index('ix_movie_credits_tmdb_id', 'movie_credits', ['tmdb_id'], unique=False)
    op.create_table('movie_genres',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tmdb_id', 'genre_id')
    )
    op.create_index('ix_movie_genres_genre_id', 'movie_genres', ['genre_id'], unique=False)
    op.create_table('movie_keywords',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tmdb_id', 'keyword_id')
    )
    op.create_index('ix_movie_keywords_keyword_id', 'movie_keywords', ['keyword_id'], unique=False)
    op.create_table('movies',
    sa.Column('row_index', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('release_year', sa.SmallInteger(), nullable=True),
    sa.Column('runtime', sa.SmallInteger(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('budget', sa.BigInteger(), nullable=True),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.Column('original_language', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('homepage', sa.String(length=500), nullable=True),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('backdrop_path', sa.String(length=255), nullable=True),
    sa.Column('adult', sa.Boolean(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('row_index')
    )
    op.create_index('ix_movies_browse', 'movies', ['adult', 'vote_count', 'popularity'], unique=False)
    op.create_index('ix_movies_original_language', 'movies', ['original_language'], unique=False)
    op.create_index('ix_movies_popularity', 'movies', ['popularity'], unique=False)
    op.create_index('ix_movies_release_date', 'movies', ['release_date'], unique=False)
    op.create_index('ix_movies_release_year', 'movies', ['release_year'], unique=False)
    op.create_index('ix_movies_title_trgm', 'movies', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('ix_movies_tmdb_id', 'movies', ['tmdb_id'], unique=False)
    op.create_index('ix_movies_vote_average', 'movies', ['vote_average'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movies_vote_average', table_name='movies')
    op.drop_index('ix_movies_tmdb_id', table_name='movies')
    op.drop_index('ix_movies_title_trgm', table_name='movies', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_movies_release_year', table_name='movies')
    op.drop_index('ix_movies_release_date', table_name='movies')
    op.drop_index('ix_movies_popularity', table_name='movies')
    op.drop_index('ix_movies_original_language', table_name='movies')
    op.drop_index('ix_movies_browse', table_name='movies')
    op.drop_table('movies')
    op.drop_index('ix_movie_keywords_keyword_id', table_name='movie_keywords')
    op.drop_table('movie_keywords')
    op.drop_index('ix_movie_genres_genre_id', table_name='movie_genres')
    op.drop_table('movie_genres')
    op.drop_index('ix_movie_credits_tmdb_id', table_name='movie_credits')
    op.drop_index('ix_movie_credits_role', table_name='movie_credits')
    op.drop_index('ix_movie_credits_person_id', table_name='movie_credits')
    op.drop_table('movie_credits')
    op.drop_index('ix_people_name', table_name='people')
    op.drop_table('people')
    op.drop_index('ix_movie_links_movielens_id', table_name='movie_links')
    op.drop_table('movie_links')
    op.drop_index('ix_keywords_name', table_name='keywords')
    op.drop_table('keywords')
    op.drop_table('genres')
    op.drop_table('collections')
    # ### end Alembic commands ###
