"""movie media cache

Revision ID: 43bb4263f09e
Revises: 299947282066
Create Date: 2026-09-20 10:00:36.039855

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '43bb4263f09e'
down_revision: Union[str, None] = '299947282066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_media',
    sa.Column('tmdb_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('backdrop_path', sa.String(length=255), nullable=True),
    sa.Column('trailer_key', sa.String(length=64), nullable=True),
    sa.Column('trailer_site', sa.String(length=32), nullable=True),
    sa.Column('trailer_type', sa.String(length=32), nullable=True),
    sa.Column('trailer_name', sa.String(length=300), nullable=True),
    sa.Column('resolution', sa.String(length=16), nullable=False),
    sa.Column('fetch_error', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('not_found', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('tmdb_id')
    )
    op.create_index('ix_movie_media_fetched_at', 'movie_media', ['fetched_at'], unique=False)
    op.create_index('ix_movie_media_resolution', 'movie_media', ['resolution'], unique=False)
    op.create_index('ix_movie_media_trailer_key', 'movie_media', ['trailer_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movie_media_trailer_key', table_name='movie_media')
    op.drop_index('ix_movie_media_resolution', table_name='movie_media')
    op.drop_index('ix_movie_media_fetched_at', table_name='movie_media')
    op.drop_table('movie_media')
    # ### end Alembic commands ###
