"""watch progress and events

Revision ID: 802b6b559b6b
Revises: 6dc767895e56
Create Date: 2026-09-20 11:13:32.440748

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '802b6b559b6b'
down_revision: Union[str, None] = '6dc767895e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('position_seconds', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['row_index'], ['movies.row_index'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watch_events_row_index', 'watch_events', ['row_index'], unique=False)
    op.create_index('ix_watch_events_user_created', 'watch_events', ['user_id', 'created_at'], unique=False)
    op.create_table('watch_progress',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('position_seconds', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('first_watched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['row_index'], ['movies.row_index'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'row_index', name='uq_watch_progress_user_movie')
    )
    op.create_index('ix_watch_progress_row_index', 'watch_progress', ['row_index'], unique=False)
    op.create_index('ix_watch_progress_user_updated', 'watch_progress', ['user_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_watch_progress_user_updated', table_name='watch_progress')
    op.drop_index('ix_watch_progress_row_index', table_name='watch_progress')
    op.drop_table('watch_progress')
    op.drop_index('ix_watch_events_user_created', table_name='watch_events')
    op.drop_index('ix_watch_events_row_index', table_name='watch_events')
    op.drop_table('watch_events')
    # ### end Alembic commands ###
